# ============================================================================
# Cloudflare Workers Configuration for Avanta Finance
# ============================================================================
# 
# This configuration file defines the settings for deploying Avanta Finance
# to Cloudflare Pages with Workers Functions, D1 Database, and R2 Storage.
#
# Documentation: https://developers.cloudflare.com/workers/wrangler/configuration/
#
# Implementation Plan V9: Phase 46 - Integration Testing & Quality Assurance
# Database: 43 tables + 7 views | API Endpoints: 78+ | Components: 114+
#
# ============================================================================

# Application name (must be unique across Cloudflare)
name = "avanta-coinmaster"

# Compatibility date determines which Cloudflare Workers runtime features are available
# Format: YYYY-MM-DD
# See: https://developers.cloudflare.com/workers/platform/compatibility-dates/
compatibility_date = "2024-01-01"

# ============================================================================
# CLOUDFLARE PAGES CONFIGURATION
# ============================================================================

# Directory containing the built static assets
# This is where Vite outputs the production build
pages_build_output_dir = "dist"

# ============================================================================
# D1 DATABASE BINDING (SQLite at the Edge)
# ============================================================================
# 
# D1 is Cloudflare's distributed SQLite database running at the edge.
# It provides low-latency SQL database access from Workers.
#
# Current Database State (Implementation Plan V9):
# - 43 Tables: users, transactions, accounts, categories, invoices, etc.
# - 7 Views: Optimized views for reporting and analytics
# - 46 Migration Files: Complete database evolution history
# - Health Monitoring: Comprehensive database health checks
#
# Setup Instructions:
# 1. Create the database:
#    wrangler d1 create avanta-coinmaster
# 
# 2. Copy the database_id from the output and replace the placeholder below
#
# 3. Run migrations to create tables:
#    wrangler d1 execute avanta-coinmaster --file=schema.sql
#    wrangler d1 execute avanta-coinmaster --file=migrations/001_initial_schema.sql
#    # ... apply all 46 migrations in order
#
# 4. (Optional) Load seed data:
#    wrangler d1 execute avanta-coinmaster --file=seed.sql
#
# Local Development:
#   wrangler pages dev dist --d1 DB=avanta-coinmaster
#
# Database Operations:
#   List databases:     wrangler d1 list
#   Query database:     wrangler d1 execute avanta-coinmaster --command="SELECT * FROM transactions LIMIT 5"
#   Backup database:    wrangler d1 export avanta-coinmaster --output=backup.sql
#   Health check:       curl http://127.0.0.1:8788/api/health
#
# Free Tier Limits:
#   - Storage: 5 GB
#   - Reads: 5 million per day
#   - Writes: 100,000 per day
#
# ============================================================================

# D1 Database binding for local development
[[d1_databases]]
binding = "DB"
database_name = "avanta-coinmaster"
database_id = "04aff2ec-b447-4af7-ae5d-0363bf6c8e49"

# ============================================================================
# R2 STORAGE BINDING (S3-Compatible Object Storage)
# ============================================================================
#
# R2 is Cloudflare's object storage service for files, images, and documents.
# It's S3-compatible with zero egress fees.
#
# Setup Instructions:
# 1. Create the R2 bucket:
#    wrangler r2 bucket create avanta-receipts
#
# 2. The bucket will be automatically bound based on the configuration below
#
# Local Development:
#   wrangler pages dev dist --r2 RECEIPTS=avanta-receipts
#
# R2 Operations:
#   List buckets:       wrangler r2 bucket list
#   List objects:       wrangler r2 object list avanta-receipts
#   Delete bucket:      wrangler r2 bucket delete avanta-receipts
#
# Free Tier Limits:
#   - Storage: 10 GB
#   - Class A Operations: 1 million per month (writes)
#   - Class B Operations: 10 million per month (reads)
#   - Egress: FREE (no data transfer fees)
#
# ============================================================================

# R2 Bucket binding moved to [env.production] section below

# ============================================================================
# ENVIRONMENT VARIABLES
# ============================================================================
#
# These variables are accessible in Workers code via env.VARIABLE_NAME
# They can be overridden per environment (production, preview)
#
# ============================================================================

[vars]
# Environment identifier
ENVIRONMENT = "production"

# Application version (update with each deployment)
APP_VERSION = "1.0.0"

# Implementation Plan V9 Status
IMPLEMENTATION_PLAN = "V9"
CURRENT_PHASE = "48.5"
PHASE_NAME = "Critical Performance Quick Wins"

# Database Health Monitoring
DB_HEALTH_MONITORING = "true"
DB_SCHEMA_VALIDATION = "true"
DB_MIGRATION_TRACKING = "true"

# API Configuration
API_TIMEOUT_MS = "30000"

# Feature flags (can be toggled without code changes)
ENABLE_DEBUG_LOGS = "false"
ENABLE_RATE_LIMITING = "false"
ENABLE_ANALYTICS = "true"

# Database Configuration
DB_QUERY_TIMEOUT_MS = "5000"
DB_MAX_RETRIES = "3"

# File Upload Configuration
MAX_FILE_SIZE_MB = "10"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/gif,application/pdf,text/xml"

# Fiscal Configuration (Mexican Tax System)
ISR_RATE = "0.20"  # 20% ISR rate (simplified)
IVA_RATE = "0.16"  # 16% IVA rate

# Phase 31: Rate Limiting Configuration
RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
RATE_LIMIT_AUTH_REQUESTS = "5"
RATE_LIMIT_WRITE_REQUESTS = "50"

# Phase 31: Caching Configuration
CACHE_TTL_SECONDS = "300"
CACHE_DASHBOARD_TTL = "300"
CACHE_REPORTS_TTL = "600"

# JWT Secret for authentication
JWT_SECRET = "avanta-coinmaster-secret-key-change-in-production"

# n8n Webhook Configuration
# N8N_WEBHOOK_CLASSIFY = "https://n8n.your-domain.com/webhook/classify"
# N8N_WEBHOOK_IMPORT = "https://n8n.your-domain.com/webhook/import"
# N8N_NOTIFICATION_WEBHOOK = "https://n8n.your-domain.com/webhook/notify"
# N8N_REMINDER_WEBHOOK = "https://n8n.your-domain.com/webhook/reminder"

# Phase 31: Error Monitoring Webhooks
# ERROR_ALERT_WEBHOOK = "https://n8n.your-domain.com/webhook/errors"
# SECURITY_ALERT_WEBHOOK = "https://n8n.your-domain.com/webhook/security"

# Phase 32: OCR Service Configuration (Optional)
# Configure external OCR service for document processing
# Option 1: Google Cloud Vision API
# GOOGLE_CLOUD_VISION_API_KEY = "your-api-key-here"
# Option 2: AWS Textract
# AWS_TEXTRACT_ENABLED = "true"
# AWS_ACCESS_KEY_ID = "your-access-key"
# AWS_SECRET_ACCESS_KEY = "your-secret-key"
# AWS_REGION = "us-east-1"

# Note: Use wrangler secret for sensitive values:
# wrangler secret put N8N_WEBHOOK_SECRET
# wrangler secret put ERROR_ALERT_WEBHOOK
# wrangler secret put SECURITY_ALERT_WEBHOOK
# wrangler secret put GOOGLE_CLOUD_VISION_API_KEY
# wrangler secret put AWS_ACCESS_KEY_ID
# wrangler secret put AWS_SECRET_ACCESS_KEY

# ============================================================================
# PREVIEW ENVIRONMENT VARIABLES (for staging/testing)
# ============================================================================
# 
# These override the main [vars] when deploying to preview branches
#
# ============================================================================

[env.preview.vars]
ENVIRONMENT = "preview"
ENABLE_DEBUG_LOGS = "true"
ENABLE_RATE_LIMITING = "false"
APP_VERSION = "1.0.0"
API_TIMEOUT_MS = "30000"
ENABLE_ANALYTICS = "false"
DB_QUERY_TIMEOUT_MS = "5000"
DB_MAX_RETRIES = "3"
MAX_FILE_SIZE_MB = "10"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/gif,application/pdf,text/xml"
ISR_RATE = "0.20"
IVA_RATE = "0.16"
RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
RATE_LIMIT_AUTH_REQUESTS = "5"
RATE_LIMIT_WRITE_REQUESTS = "50"
CACHE_TTL_SECONDS = "300"
CACHE_DASHBOARD_TTL = "300"
CACHE_REPORTS_TTL = "600"

# Implementation Plan V9 Status (required for preview environment)
IMPLEMENTATION_PLAN = "V9"
CURRENT_PHASE = "48.5"
PHASE_NAME = "Critical Performance Quick Wins"

# Database Health Monitoring (required for preview environment)
DB_HEALTH_MONITORING = "true"
DB_SCHEMA_VALIDATION = "true"
DB_MIGRATION_TRACKING = "true"

# ============================================================================
# CRITICAL: PREVIEW ENVIRONMENT DATABASE ISOLATION
# ============================================================================
# 
# PHASE 30 REQUIREMENT: Preview must use a SEPARATE database from production
# to prevent cross-environment data contamination.
#
# ✅ STATUS: Environment isolation COMPLETE
# - Dedicated preview database created: avanta-coinmaster-preview
# - Database ID: fb173697-b916-4ab9-a244-88e657fdcb9d
# - Migrations applied to preview database
# - Environment isolation verified
#
# ✅ VERIFICATION COMPLETE:
# - Preview deployments write to the preview database only
# - Production database is never accessed from preview environment
# - Preview can be reset without affecting production
#
# ============================================================================

# D1 Database binding for preview environment
# ✅ COMPLETE: Using dedicated preview database for environment isolation
[[env.preview.d1_databases]]
binding = "DB"
database_name = "avanta-coinmaster-preview"
database_id = "fb173697-b916-4ab9-a244-88e657fdcb9d"

# R2 Bucket binding for preview environment
# Using the same bucket as production with preview/ prefix for file paths
[[env.preview.r2_buckets]]
binding = "RECEIPTS"
bucket_name = "avanta-receipts"

# ============================================================================
# PRODUCTION ENVIRONMENT (explicit configuration)
# ============================================================================

[env.production.vars]
ENVIRONMENT = "production"
ENABLE_DEBUG_LOGS = "false"
ENABLE_RATE_LIMITING = "true"
ENABLE_ANALYTICS = "true"
APP_VERSION = "1.0.0"
API_TIMEOUT_MS = "30000"
DB_QUERY_TIMEOUT_MS = "10000"
DB_MAX_RETRIES = "3"
MAX_FILE_SIZE_MB = "10"
ALLOWED_FILE_TYPES = "pdf,jpg,jpeg,png,xml,csv"
ISR_RATE = "0.20"
IVA_RATE = "0.16"

# Implementation Plan V9 Status
IMPLEMENTATION_PLAN = "V9"
CURRENT_PHASE = "48.5"
PHASE_NAME = "Critical Performance Quick Wins"

# Database Health Monitoring
DB_HEALTH_MONITORING = "true"
DB_SCHEMA_VALIDATION = "true"
DB_MIGRATION_TRACKING = "true"

# Rate Limiting Configuration
RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
RATE_LIMIT_AUTH_REQUESTS = "5"
RATE_LIMIT_WRITE_REQUESTS = "50"

# Caching Configuration
CACHE_TTL_SECONDS = "300"
CACHE_DASHBOARD_TTL = "300"
CACHE_REPORTS_TTL = "600"

# D1 Database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "avanta-coinmaster"
database_id = "04aff2ec-b447-4af7-ae5d-0363bf6c8e49"

# R2 Bucket binding for production
[[env.production.r2_buckets]]
binding = "RECEIPTS"
bucket_name = "avanta-receipts"

# ============================================================================
# WORKERS FUNCTIONS CONFIGURATION
# ============================================================================
#
# Configuration for Cloudflare Pages Functions (Workers)
# Functions are automatically deployed from the /functions directory
#
# Current API Endpoints (78+ total):
#   /api/dashboard        - GET: Financial dashboard summary
#   /api/transactions     - GET, POST: List/Create transactions
#   /api/transactions/:id - GET, PUT, DELETE: Single transaction operations
#   /api/accounts         - GET: List accounts
#   /api/accounts/:id     - PUT: Update account balance
#   /api/fiscal           - GET: Tax calculations (ISR, IVA)
#   /api/invoices         - GET, POST: CFDI invoice management
#   /api/upload           - POST: File upload to R2
#   /api/health           - GET: Database health monitoring
#   /api/monitoring/health - GET: Enhanced health checks
#   /api/users            - GET, POST, PUT: User management
#   /api/categories       - GET, POST, PUT, DELETE: Category management
#   /api/budgets          - GET, POST, PUT, DELETE: Budget management
#   /api/credits          - GET, POST, PUT, DELETE: Credit management
#   /api/receipts         - GET, POST, PUT, DELETE: Receipt management
#   /api/audit-log        - GET: Audit logging
#   /api/help             - GET: Help system
#   /api/tasks            - GET, POST, PUT, DELETE: Task management
#   /api/demo             - GET, POST: Demo system
#   ... and 60+ more endpoints
#
# ============================================================================

# ============================================================================
# ADVANCED CONFIGURATION (Optional)
# ============================================================================

# Limits and Performance
# [limits]
# CPU time limit per request (in milliseconds, max 30000 for Bundled)
# cpu_ms = 50

# Observability Configuration
# [observability]
# enabled = true
# head_sampling_rate = 1

# Custom Routes (if needed)
# [[routes]]
# pattern = "/api/*"
# custom_domain = true

# ============================================================================
# DEPLOYMENT INSTRUCTIONS
# ============================================================================
#
# Implementation Plan V9 Deployment Instructions:
#   1. Install dependencies:         npm install
#   2. Build the application:        npm run build
#   3. Start dev server:             npm run dev
#   4. Preview with Workers:         npx wrangler pages dev dist --d1 DB=avanta-coinmaster --r2 RECEIPTS=avanta-receipts
#   5. Test database health:         curl http://127.0.0.1:8788/api/health
#
# Production Deployment:
#   1. Login to Cloudflare:          wrangler login
#   2. Verify D1 database:           wrangler d1 list
#   3. Check database health:         wrangler d1 execute avanta-coinmaster --command="SELECT COUNT(*) FROM sqlite_master WHERE type='table'"
#   4. Verify all 43 tables exist:   wrangler d1 execute avanta-coinmaster --command="SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
#   5. Verify all 7 views exist:      wrangler d1 execute avanta-coinmaster --command="SELECT name FROM sqlite_master WHERE type='view' ORDER BY name"
#   6. Build application:             npm run build
#   7. Deploy to Pages:              wrangler pages deploy dist
#   8. Test health endpoint:          curl https://avanta-coinmaster.pages.dev/api/health
#
# Continuous Deployment:
#   - Push to main branch triggers automatic deployment via Cloudflare Pages
#   - Database health monitoring active
#   - 78+ API endpoints automatically deployed
#   - 114+ React components built and optimized
#
# Troubleshooting:
#   - List databases:     wrangler d1 list
#   - List buckets:       wrangler r2 bucket list
#   - View logs:          wrangler pages deployment tail
#   - Test database:      wrangler d1 execute avanta-coinmaster --command="SELECT COUNT(*) FROM sqlite_master WHERE type='table'"
#   - Health check:        curl https://avanta-coinmaster.pages.dev/api/health
#   - Test API:            curl https://avanta-coinmaster.pages.dev/api/dashboard
#   - Check migrations:    ls migrations/ | wc -l (should show 46)
#   - Verify components:   npm run build (should build 114+ components)
#
# Documentation:
#   - Wrangler:          https://developers.cloudflare.com/workers/wrangler/
#   - D1:                https://developers.cloudflare.com/d1/
#   - R2:                https://developers.cloudflare.com/r2/
#   - Pages Functions:   https://developers.cloudflare.com/pages/functions/
#
# ============================================================================

# ============================================================================
# PHASE 31: PRODUCTION INFRASTRUCTURE (OPTIONAL)
# ============================================================================
#
# These bindings are OPTIONAL for production deployments.
# The application works with in-memory implementations by default.
# Uncomment and configure these for production-grade distributed storage.
#
# See PHASE_31_PRODUCTION_INFRASTRUCTURE.md for complete setup instructions.
# ============================================================================

# Phase 31: KV Namespace for Distributed Caching (OPTIONAL)
# Uncomment after creating KV namespace with: wrangler kv:namespace create "CACHE_KV"
# [[kv_namespaces]]
# binding = "CACHE_KV"
# id = "your-kv-namespace-id-here"
# preview_id = "your-preview-kv-namespace-id-here"

# Phase 31: Durable Objects for Distributed Rate Limiting (OPTIONAL)
# Uncomment after creating Durable Object class in functions/durable-objects/rate-limiter.js
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"
# script_name = "avanta-coinmaster"

# Phase 31: Durable Objects Migration (OPTIONAL)
# Uncomment when deploying Durable Objects for the first time
# [[migrations]]
# tag = "v1"
# new_classes = ["RateLimiter"]

# ============================================================================
# NOTES
# ============================================================================
#
# 1. Database ID: Must be replaced with actual ID from `wrangler d1 create`
# 2. Bindings: Ensure D1 and R2 bindings are configured in Cloudflare Dashboard
# 3. Secrets: For sensitive data, use `wrangler secret put` instead of vars
# 4. Custom Domain: Configure in Cloudflare Dashboard under Pages settings
# 5. Analytics: Enable in Cloudflare Dashboard for detailed metrics
# 6. Phase 31: KV and Durable Objects are OPTIONAL - app works without them
#
# ============================================================================
