name = "avanta-finance"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "avanta-finance"
# TODO: Replace the placeholder below with the actual database ID from `wrangler d1 create`
database_id = "your-database-id-here"

# R2 Bucket binding
[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "avanta-receipts"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"
